---
title: "learnrhash - Minimal"
output: learnr::tutorial
runtime: shiny_prerendered
tutorial:
  id: "demo-iframe"
  version: 1.0
---

```{r setup, include=FALSE}
library(learnr)
```

## Question

```{r planets, echo=FALSE}
question(
  "Which planet do we live on?",
  answer("Mars",   correct = FALSE),
  answer("Earth",  correct = TRUE),
  answer("Saturn", correct = FALSE),
  allow_retry = TRUE
)
```

## Submit

```{r context="server"}
learnrhash::encoder_logic()
```

Note the following may not show in RStudio's viewer, try opening it in your browser to see the full iframe.

```{r encode, echo=FALSE}
learnrhash::encoder_ui(
  ui_before = shiny::div(
    "If you have completed this tutorial and are happy with all of your",
    "solutions, please click the button below to generate your hash and",
    "submit it using the following form:",
    shiny::tags$br()
  ), 
  ui_after = learnrhash::iframe_ui(
    src = "https://docs.google.com/forms/d/e/1FAIpQLSdzre-kmqNje64ZCK7VsXHWKSVdGNOjSUwU1IZaCWs_vL_yuQ/viewform?embedded=true",
    width="640px", height= "800px", frameborder="0", marginheight="0", marginwidth="0"
  )
)
```

